name: Build and Export

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Clean install dependencies
        run: |
          rm -rf node_modules package-lock.json
          npm install
          
      - name: Build
        run: |
          npm run build
          npm run export
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: out
          path: ./out
